[package]
name = "term-sdk-examples"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "simple_agent"
path = "simple_agent.rs"

[[bin]]
name = "llm_agent"
path = "llm_agent.rs"

[dependencies]
term-sdk = { path = "../../rust" }
